# Generated by Django 3.2.7 on 2021-11-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
